version: '2'
services:
    selenium-hub:
        image: selenium/hub
        container_name: 'selenium-hub'
        ports:
            - '4444:4444'

    chrome:
        image: selenium/node-chrome-debug
        container_name: 'chrome'
        environment:
            - HUB_PORT_4444_TCP_ADDR=selenium-hub
            - HUB_PORT_4444_TCP_PORT=4444
        ports:
            - '5900:5900'
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub

    python3-selenium:
        build: .
        container_name: 'python3-selenium'
        working_dir: '/root/'
        command: 'tail -f /dev/null'
        volumes:
            - ./opt/:/root/opt/